Repository valeriyvan/swift-geometrize, pull requests merged in 2023-10, with the labels that each got.

#49 Make alpha UInt8 everywhere
  Sources/geometrize/Core.swift
  Sources/geometrize/GeometrizeModelHillClimb.swift
Labels: hacktoberfest-accepted, hacktoberfest

#53 Get rid of arrays of the only element
  Sources/geometrize-cli/main.swift
  Sources/geometrize/GeometrizeModelHillClimb.swift
  Sources/geometrize/ImageRunner.swift
  Tests/geometrizeTests/ImageRunnerTests.swift
Labels: hacktoberfest-accepted, hacktoberfest

#57 Add multithreading
  README.md
  Sources/geometrize/Core.swift
  Sources/geometrize/GeometrizeModelHillClimb.swift
  Sources/geometrize/Int_random.swift
  Sources/geometrize/ShapeCreator.swift
Labels: enhancement

#60 Move EnergyFunction into separate file
  Sources/geometrize/Core.swift
  Sources/geometrize/EnergyFunction.swift
Labels: hacktoberfest-accepted, hacktoberfest

#61 Move computeColor to extansion [Scanline]
  Sources/geometrize/Core.swift
  Sources/geometrize/EnergyFunction.swift
  Sources/geometrize/GeometrizeModelHillClimb.swift
  Sources/geometrize/Scanline.swift
Labels: hacktoberfest-accepted, hacktoberfest, refactor

#62 Rename Core.swift -> HillClimb.swift
  Sources/geometrize/HillClimb.swift
  Sources/geometrize/Scanline.swift
Labels: refactor

#65 Refine parameter description
  Sources/geometrize-cli/main.swift
Labels: bug

#69 Fix bug rasterizing ellipse
  Sources/geometrize/Shapes/Ellipse.swift
Labels: bug, hacktoberfest-accepted, hacktoberfest

#71 Fix bug setting up line
  Sources/geometrize/Shapes/Line.swift
Labels: bug, hacktoberfest-accepted, hacktoberfest

#75 Change bresenham line drawing implementation with robust one supporting thickness and overlap modes.
  Sources/geometrize/Polygon.swift
  Sources/geometrize/Shapes/Line.swift
  Sources/geometrize/Shapes/Polyline.swift
  Sources/geometrize/Shapes/QuadraticBezier.swift
  Sources/geometrize/bresenham.swift
  Tests/geometrizeTests/__Snapshots__/QuadraticBezierTests/testRasterize.1.png
  Tests/geometrizeTests/__Snapshots__/bresenhamTests/testBresenham.1.png
  Tests/geometrizeTests/__Snapshots__/bresenhamTests/testBresenhamThickness.1.png
  Tests/geometrizeTests/bresenhamTests.swift
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#79 Refactor line drawing functions
  Sources/geometrize/bresenham.swift
Labels: hacktoberfest-accepted, hacktoberfest, refactor

#55 Delete .swiftpm directory
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  .swiftpm/xcode/xcshareddata/xcschemes/geometrize-Package.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/geometrize-cli.xcscheme
Labels: hacktoberfest-accepted, hacktoberfest

#80 Rename build-run-tests.yml workflow
  .github/workflows/build-run-tests.yml
Labels: ci/cd

#81 Add build&test badge
  README.md
Labels: documentation, ci/cd

#83 Fix syntax error in build-run-tests-ubuntu.yml
  .github/workflows/build-run-tests-ubuntu.yml
Labels: ci/cd

#86 Update build-run-tests-ubuntu.yml
  .github/workflows/build-run-tests-ubuntu.yml
Labels: ci/cd

#87 Turn off test on Ubuntu
  .github/workflows/build-run-tests-ubuntu.yml
Labels: ci/cd

#92 Use strokeWidth in Line, Polyline, QuadraticBezier
  Sources/geometrize-cli/main.swift
  Sources/geometrize/ImageRunner.swift
  Sources/geometrize/SVGExporter.swift
  Sources/geometrize/ShapeCreator.swift
  Sources/geometrize/Shapes/Circle.swift
  Sources/geometrize/Shapes/Ellipse.swift
  Sources/geometrize/Shapes/Line.swift
  Sources/geometrize/Shapes/Polyline.swift
  Sources/geometrize/Shapes/QuadraticBezier.swift
  Sources/geometrize/Shapes/Rectangle.swift
  Sources/geometrize/Shapes/RotatedEllipse.swift
  Sources/geometrize/Shapes/RotatedRectangle.swift
  Sources/geometrize/Shapes/Shape.swift
  Sources/geometrize/Shapes/Triangle.swift
  Tests/geometrizeTests/BitmapDownsampleTests.swift
  Tests/geometrizeTests/CircleTest.swift
  Tests/geometrizeTests/CoreTests.swift
  Tests/geometrizeTests/EllipseTests.swift
  Tests/geometrizeTests/ImageRunnerTests.swift
  Tests/geometrizeTests/LineTests.swift
  Tests/geometrizeTests/QuadraticBezierTests.swift
  Tests/geometrizeTests/TriangleTests.swift
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#93 Refactor geometrize-cli main function
  Sources/geometrize-cli/main.swift
Labels: refactor

#95 Replace precondition with assert
  Sources/geometrize/ImageRunner.swift
Labels: refactor

#96 Move Bounds out of Shapes
  Sources/geometrize/Bounds.swift
Labels: refactor

#97 Clear Shape.swift
  Sources/geometrize/Shapes/ArrayString-shapeTypes.swift
  Sources/geometrize/Shapes/Shape.swift
  Sources/geometrize/Shapes/allShapeTypes.swift
Labels: refactor
